"""add cv tags

Revision ID: c0d3b908a35d
Revises: fb34b95e87c1
Create Date: 2025-09-06 06:23:32.830521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d3b908a35d'
down_revision = 'fb34b95e87c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    op.create_index(op.f('ix_vacancy_tags'), 'vacancy', ['tags'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_tags'), table_name='vacancy')
    op.drop_column('vacancy', 'tags')
    # ### end Alembic commands ###
