"""add interview tables

Revision ID: d3d93ff2221f
Revises: c0d3b908a35d
Create Date: 2025-09-06 15:32:27.502091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d93ff2221f'
down_revision = 'c0d3b908a35d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_script',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('script', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_script_id'), 'interview_script', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_script_id'), table_name='interview_script')
    op.drop_table('interview_script')
    # ### end Alembic commands ###
