"""add cv parsing fields

Revision ID: fb34b95e87c1
Revises: 7c8716681295
Create Date: 2025-09-05 19:35:36.203950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb34b95e87c1'
down_revision = '7c8716681295'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('cv', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('cv', sa.Column('telegram', sa.String(length=30), nullable=True))
    op.add_column('cv', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    op.create_index(op.f('ix_cv_tags'), 'cv', ['tags'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_tags'), table_name='cv')
    op.drop_column('cv', 'tags')
    op.drop_column('cv', 'telegram')
    op.drop_column('cv', 'email')
    op.drop_column('cv', 'phone_number')
    # ### end Alembic commands ###
